import Link from "next/link"
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body>
  <nav className="border-b px-8 py-4">
    <div className="mx-auto flex max-w-5xl gap-6">
      <Link href="/">Home</Link>
      <Link href="/about">About</Link>
      <Link href="/demo">Demo</Link>
      <Link href="/contact">Contact</Link>
    </div>
  </nav>
  {children}
</body>
    </html>
  );
}
